using DataAccessLayer;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace PresentationLayer.Services;

public interface IResearchReportPdfService
{
    byte[] BuildReport(ResearchExperimentDetail experiment);
}

public sealed class ResearchReportPdfService : IResearchReportPdfService
{
    public byte[] BuildReport(ResearchExperimentDetail experiment)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(32);
                page.DefaultTextStyle(text => text.FontSize(10).FontFamily("Arial"));

                page.Header().Column(column =>
                {
                    column.Item().Text("RBL Benchmark Report").FontSize(20).Bold().FontColor(Colors.Blue.Darken4);
                    column.Item().Text($"{experiment.Name} | {experiment.Subject}").FontSize(11).FontColor(Colors.Grey.Darken2);
                    column.Item().PaddingTop(4).LineHorizontal(1).LineColor(Colors.Grey.Lighten1);
                });

                page.Content().PaddingVertical(16).Column(column =>
                {
                    column.Spacing(14);
                    column.Item().Element(element => BuildSummary(element, experiment));
                    column.Item().Element(element => BuildRunTable(element, experiment.Runs));
                    column.Item().Element(element => BuildQuestionTable(element, experiment.Questions));
                });

                page.Footer().AlignRight().Text(text =>
                {
                    text.Span("Generated by EdTech AI RBL - ");
                    text.CurrentPageNumber();
                    text.Span("/");
                    text.TotalPages();
                });
            });
        }).GeneratePdf();
    }

    private static void BuildSummary(IContainer container, ResearchExperimentDetail experiment)
    {
        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn();
                columns.RelativeColumn();
            });

            SummaryCell(table, "Status", experiment.Status);
            SummaryCell(table, "Runs", experiment.RunCount.ToString());
            SummaryCell(table, "Questions", experiment.QuestionCount.ToString());
            SummaryCell(table, "Avg RAGAS", experiment.AverageRagasScore?.ToString("0.000") ?? "-");
        });
    }

    private static void SummaryCell(TableDescriptor table, string label, string value)
    {
        table.Cell().Padding(8).Border(1).BorderColor(Colors.Grey.Lighten1).Column(column =>
        {
            column.Item().Text(label).FontSize(8).FontColor(Colors.Grey.Darken1);
            column.Item().Text(value).FontSize(13).Bold().FontColor(Colors.Blue.Darken4);
        });
    }

    private static void BuildRunTable(IContainer container, IReadOnlyList<ResearchRunSummary> runs)
    {
        container.Column(column =>
        {
            column.Item().Text("RAGAS benchmark table").FontSize(14).Bold().FontColor(Colors.Blue.Darken4);
            column.Item().PaddingTop(6).Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(2.3f);
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                    columns.RelativeColumn();
                });

                Header(table, "Run");
                Header(table, "Type");
                Header(table, "Status");
                Header(table, "Latency");
                Header(table, "Faith");
                Header(table, "Relevant");
                Header(table, "Ctx P");
                Header(table, "Ctx R");
                Header(table, "RAGAS");

                foreach (var run in runs)
                {
                    Cell(table, run.RunName);
                    Cell(table, run.RunKind);
                    Cell(table, run.Status);
                    Cell(table, run.AverageLatencyMs?.ToString("0") ?? "-");
                    Cell(table, run.AverageFaithfulness?.ToString("0.000") ?? "-");
                    Cell(table, run.AverageAnswerRelevancy?.ToString("0.000") ?? "-");
                    Cell(table, run.AverageContextPrecision?.ToString("0.000") ?? "-");
                    Cell(table, run.AverageContextRecall?.ToString("0.000") ?? "-");
                    Cell(table, run.AverageRagasScore?.ToString("0.000") ?? "-");
                }
            });
        });
    }

    private static void BuildQuestionTable(IContainer container, IReadOnlyList<ResearchTestQuestion> questions)
    {
        container.Column(column =>
        {
            column.Item().Text("Test questions").FontSize(14).Bold().FontColor(Colors.Blue.Darken4);
            column.Item().PaddingTop(6).Table(table =>
            {
                table.ColumnsDefinition(columns =>
                {
                    columns.RelativeColumn(2);
                    columns.RelativeColumn(2);
                    columns.RelativeColumn();
                });

                Header(table, "Question");
                Header(table, "Ground truth");
                Header(table, "Difficulty");

                foreach (var question in questions)
                {
                    Cell(table, question.Question);
                    Cell(table, question.GroundTruth);
                    Cell(table, question.Difficulty);
                }
            });
        });
    }

    private static void Header(TableDescriptor table, string text)
    {
        table.Cell()
            .Background(Colors.Blue.Darken4)
            .Padding(6)
            .Text(text)
            .FontColor(Colors.White)
            .Bold();
    }

    private static void Cell(TableDescriptor table, string text)
    {
        table.Cell()
            .BorderBottom(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(6)
            .Text(string.IsNullOrWhiteSpace(text) ? "-" : text)
            .FontSize(8);
    }
}
